version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: develop.Dockerfile
    container_name: webpack-portfolio-web
    volumes: 
      - ".:/app"
    env_file:
      - '.env.development'
    ports:
      - "3001:3000"
    tty: true