apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-01-03T00:05:40Z"
  generation: 1
  labels:
    app: webpack-portfolio-web
  name: webpack-portfolio-web
  namespace: default
  resourceVersion: "521"
  uid: e0aa793f-a94e-4582-a234-ade4df7467e1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: webpack-portfolio-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webpack-portfolio-web
    spec:
      containers:
      - image: caprilespe/webpack-portfolio-web:v1
        imagePullPolicy: IfNotPresent
        name: webpack-portfolio-web
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-01-03T00:05:49Z"
    lastUpdateTime: "2022-01-03T00:05:49Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-01-03T00:05:40Z"
    lastUpdateTime: "2022-01-03T00:05:49Z"
    message: ReplicaSet "webpack-portfolio-web-798fb44dcc" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
