name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: staging
    strategy:
      matrix:
        node-version: [15.x]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Generate build number
      run: echo "The build number $GITHUB_RUN_NUMBER 🏗"
    - name: Install dependencies
      run: npm install
    - name: Public URL
      run: export PUBLIC_URL=https://zearkiatos.github.io/webpack-portfolio-web
    - name: Create .env
      run: |
        touch .env &&
        echo "ENVIRONMENT=${ENVIRONMENT}" > .env
        echo "RANDOMUSER_API_BASE_URL=${RANDOMUSER_API_BASE_URL}" >> .env
      env:
        ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
        RANDOMUSER_API_BASE_URL: ${{ secrets.RANDOMUSER_API_BASE_URL }}
    - name: Build docker 🐳
      run: docker build . -t=webpack-portfolio-web:ghb-$GITHUB_RUN_NUMBER
    - name: Build
      run: npm run webpack:build
    - name: Upload production-ready build files
      uses: actions/upload-artifact@v2
      with:
        name: production-files
        path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: production-files
        path: ./dist

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist